# Generated by Django 2.0.5 on 2018-05-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('hindi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='marks',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='try_app1.Students'),
        ),
    ]
